vtidy + structure
Cleaned up the script.  Added vtidy to all .v and .sv files, put iverilog files into array at top of files.

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,18 +1,37 @@
-#!/bin/sh
-iverilog -DSIMULATION=1 -o out.vvp ./tb.v ./top.v
- 
-vvp out.vvp
+#!/usr/bin/env bash
 
+SIMFILES=( "./tb.v" "./top.v" )
+SIMFILES+=( "./nios_system_sdram.v" )
+
+IVERILOG='iverilog'
+SIMFLAGS='-DSIMULATION'
+SIMOUTFL='out.vvp'
+WAVEFILE='dump.vcd'
+
+# Grab the PID of GTKWAVE (if exists)
 GTKWAVEPID=`ps a | grep gtkwave | grep -v "grep" | awk '{print $1}'`
-if [ -z $GTKWAVEPID ]; then 
-    gtkwave -r gtkwaverc dump.vcd&
+
+# Compile the design simulation.
+if ! ${IVERILOG} $SIMFLAGS -o $SIMOUTFL ${SIMFILES[@]}; then
+    echo "**** Simulation failed ****"
+    exit
 fi
 
-if [ ! -z $GTKWAVEPID ]; then 
+# Clean up the RTL.
+find -name "*.v"  -exec ./bin/vtidy -n {} 1>/dev/null \;
+find -name "*.sv" -exec ./bin/vtidy -n {} 1>/dev/null \;
+
+# Execute the simulation.
+echo "########################### BEGIN SIM OUTPUT ###########################"
+vvp out.vvp
+echo "###########################  END SIM OUTPUT  ###########################"
+
+# Launch gtkwave (if not already running).
+if [ -z $GTKWAVEPID ]; then 
+    gtkwave -r gtkwaverc dump.vcd&
+else
     printf "\n"
     printf "GTKWAVE already running: $GTKWAVEPID \n"
     echo "CTRL+SHIFT+R to reload waveform in GTKWAVE"
     printf "\n"
 fi
-
-
